project:
  type: website

website:
  title: "Kay's Visual Analytics Page"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1 - A Layered Grammar of Graphics: ggplot2 methods"
        href: "HoEx/HoEx1/HoE1.html"
      - text: "Hands-on Exercise 2 - Beyond ggplot2 Fundamentals"
        href: "HoEx/HoEx2/HoE2.html"
      - text: "Hands-on Exercise 3a: Programming Interactive Data Visualisation with R"
        href: "HoEx/HoEx3/HoE3a.html"
      - text: "Hands-on Exercise 3b: Programming Animated Statistical Graphics with R"
        href: "HoEx/HoEx3/HoE3b.html"
      - text: "Hands-on Exercise 4a: Visualising Distribution"
        href: "HoEx/HoEx4/HoE4a.html"
      - text: "Hands-on Exercise 4b: Visual Statistical Analysis"
        href: "HoEx/HoEx4/HoE4b.html"
      - text: "Hands-on Exercise 4c: Visualising Uncertainty"
        href: "HoEx/HoEx4/HoE4c.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

