project:
  type: website

website:
  title: "Kay's Visual Analytics Page"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1 - A Layered Grammar of Graphics: ggplot2 methods"
        href: "HoEx/HoEx1/HoE1.qmd"
      - text: "Hands-on Exercise 2 - Beyond ggplot2 Fundamentals"
        href: "HoEx/HoEx2/HoE2.qmd"
      - text: "Hands-on Exercise 3a: Programming Interactive Data Visualisation with R"
        href: "HoEx/HoEx3/HoE3a.qmd"
      - text: "Hands-on Exercise 3b: Programming Animated Statistical Graphics with R"
        href: "HoEx/HoEx3/HoE3b.qmd"
      - text: "Hands-on Exercise 4a: Visualising Distribution"
        href: "HoEx/HoEx4/HoE4a.qmd"
      - text: "Hands-on Exercise 4b: Visual Statistical Analysis"
        href: "HoEx/HoEx4/HoE4b.qmd"
      - text: "Hands-on Exercise 4c: Visualising Uncertainty"
        href: "HoEx/HoEx4/HoE4c.qmd"
      - text: "Hands-on Exercise 4d: Funnel Plots for Fair Comparisons"
        href: "HoEx/HoEx4/HoE4d.qmd"
      - text: "Hands-on Exercise 5a: Creating Ternary Plot with R"
        href: "HoEx/HoEx5/HoE5a.qmd"
      - text: "Hands-on Exercise 5b: Visual Correlation Analysis"
        href: "HoEx/HoEx5/HoE5b.qmd"
      - text: "Hands-on Exercise 5c: Visual Multivariate Analysis with Heatmap"
        href: "HoEx/HoEx5/HoE5c.qmd"
      - text: "Hands-on Exercise 5d: Visual Multivariate Analysis with Parallel Coordinates Plot"
        href: "HoEx/HoEx5/HoE5d.qmd"
      - text: "Hands-on Exercise 5e: Treemap Visualisation with R"
        href: "HoEx/HoEx5/HoE5e.qmd"
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: "TakeHome/TakeHome1/TakeHome1.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    embed-resources: true
    theme: minty
    css: styles.css
    toc: true

editor: visual

