{
  "hash": "626033b215e7b2d17b00e0472e477737",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1\"\nauthor: \"Htet Kay Khaing\"\ndate: \"May 7, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## 1. Overview/Background\n\nMotor insurance portfolios usually contain many policies with no claims and a small number of policies with severe claim outcomes. Because of this, aggregate profitability can look acceptable even when selected segments are loss-making or highly volatile. This study uses visual analytics to examine the distribution of key variables and to identify portfolio factors that may influence profitability and volatility.\n\n## 2. The tasks\n\n1.  **Apply suitable univariate visual analytics techniques** to explore the distributions and characteristics of numerical and categorical variables.\n2.  **Apply suitable bivariate visual analytics techniques** to investigate and statistically validate factors influencing the profitability and volatility of the insurance portfolio.\n\nFor this report, **profitability** is measured mainly using `underwriting_result`, `underwriting_margin` and `loss_ratio`. **Volatility** is examined using claim occurrence, claim frequency, the spread of loss ratio and upper-tail loss ratio behaviour.\n\n::: {.callout-note}\nThe analysis is exploratory. The statistical tests validate whether observed differences are unlikely to be random, but they do not prove direct causality. Business interpretation is still required because the dataset is observational.\n:::\n\n## 3. Getting started\n\n### 3.1 Installing and loading the packages\n\nFor this exercise, the following R packages will be used:\n\n-   **tidyverse** for data wrangling and ggplot2 visualisation,\n-   **scales** for formatting values,\n-   **patchwork** for combining plots,\n-   **ggdist** for raincloud-style distribution plots,\n-   **ggridges** for ridgeline plots, and\n-   **knitr** for report formatting support.\n\nThe following code chunk uses `p_load()` of **pacman** package to check if tidyverse packages are installed in the computer. If they are, the libraries will be called into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, scales, patchwork,\n               ggdist, ggridges, knitr)\n```\n:::\n\n\n## 4. The Data\n\n### 4.1 Data import\n\nThe data file used is [Dataset of motor insurance portfolio.csv](https://data.mendeley.com/datasets/sw4jmdb2sm/1). The file is semicolon-delimited, so `read_delim()` is used instead of `read_csv()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_raw <- read_delim(\n  \"data/Dataset of motor insurance portfolio.csv\",\n  delim = \";\",\n  show_col_types = FALSE\n)\n# glimpse(motor_raw)\n```\n:::\n\n\n### 4.2 Data overview\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Dataset overview: Motor insurance portfolio transaction records\n\n|metric                |value            |\n|:---------------------|:----------------|\n|Number of records     |354,140          |\n|Number of variables   |47               |\n|Unique insured IDs    |185,678          |\n|Years covered         |2022, 2023, 2024 |\n|Total premium         |$105,079,669     |\n|Total incurred claims |$73,864,811      |\n|Total claims          |77,099           |\n|Total exposure        |250,325.9        |\n\n\n:::\n:::\n\n\nThe dataset has **354,140** records and **47** variables. It covers policy transaction records from **2022, 2023, 2024**, which allows both cross-sectional and time-based portfolio analysis.\n\n### 4.3 Data Cleaning\n\n::: {.panel-tabset}\n## Check Missing Values\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Variables with missing values\n\n|variable            |missing_records |missing_pct |\n|:-------------------|:---------------|:-----------|\n|fuel_type           |1,287           |0.36%       |\n|vehicle_value       |513             |0.14%       |\n|vehicle_age         |2               |0.00%       |\n|age_driving_licence |2               |0.00%       |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe missing value check shows that only four variables have a small portion of missing values: `fuel_type`, `vehicle_value`, `vehicle_age` and `age_driving_licence`.\n\nFor this exercise, missing values will not be removed because the main profitability and volatility measures, such as premium, claims, incurred amount and exposure, are still available. Removing rows with minor missing values may unnecessarily distort the portfolio-level analysis.\n\n## Check duplicates\nDuplicate records are checked to ensure that there are no repeated rows. If exact duplicates are found, they should be removed because they may represent repeated transaction records. However, repeated `insured_id` values alone should not be treated as duplicates, as the same customer may have multiple policy records across years or policy types.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nduplicate_records <- sum(duplicated(motor_raw))\nduplicate_pct <- duplicate_records / nrow(motor_raw)\n\nduplicate_tbl <- data.frame(\n  Check = \"Exact duplicate rows across all variables\",\n  Duplicate_Records = comma(duplicate_records),\n  Duplicate_Percentage = percent(duplicate_pct, accuracy = 0.01)\n)\n\nknitr::kable(\n  duplicate_tbl,\n  caption = \"Duplicate records check\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Duplicate records check\n\n|Check                                     |Duplicate_Records |Duplicate_Percentage |\n|:-----------------------------------------|:-----------------|:--------------------|\n|Exact duplicate rows across all variables |0                 |0.00%                |\n\n\n:::\n:::\n\n:::\n\n### 4.4 Data Preparation\n#### 4.4.1 Deriving analytical variables\nThe raw dataset includes premium, incurred claims, number of claims and exposure. To investigate profitability and volatility, derived fields are created:\n\n- `underwriting_result` = total premium minus total incurred claims,\n- `loss_ratio` = total incurred claims divided by total premium,\n- `claim_flag` = whether the record has at least one claim, and\n- `loss_ratio_capped` = loss ratio capped at the 99th percentile for visualisation readability.\n\nThese derived fields are sufficient for the study objectives. `underwriting_result` and `loss_ratio` are used to assess profitability, while `claim_flag` and `loss_ratio_capped` help examine claim occurrence and volatility. Other variables are retained in their original form to keep the analysis simple and interpretable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_prep <- mutate(\n  motor_raw,\n  year = as.factor(year),\n  policy_type = as.factor(policy_type),\n  policy_status = as.factor(policy_status),\n  business_type = as.factor(business_type),\n  payment_frequency = as.factor(payment_frequency),\n  underwriting_result = total_premium - total_incurred,\n  loss_ratio = if_else(total_premium > 0, total_incurred / total_premium, NA_real_),\n  claim_flag = total_claims > 0\n)\n\nmotor_prep <- filter(\n  motor_prep,\n  total_premium > 0,\n  total_exposure > 0\n)\n\nloss_ratio_cap_value <- quantile(motor_prep$loss_ratio, 0.99, na.rm = TRUE)\n\nmotor <- mutate(\n  motor_prep,\n  loss_ratio_capped = pmin(loss_ratio, loss_ratio_cap_value)\n)\n```\n:::\n\n\n::: {.callout-note}\n`loss_ratio_capped` is used only for visualisation and non-parametric tests. Portfolio profitability calculations still use the original premium and incurred claim values.\n:::\n\n#### 4.4.2 Portfolio-level summary\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nportfolio_summary <- summarise(\n  motor,\n  valid_records = n(),\n  unique_insured = n_distinct(insured_id),\n  total_premium = sum(total_premium, na.rm = TRUE),\n  total_incurred = sum(total_incurred, na.rm = TRUE),\n  underwriting_result = sum(underwriting_result, na.rm = TRUE),\n  loss_ratio = sum(total_incurred, na.rm = TRUE) / sum(total_premium, na.rm = TRUE),\n  total_claims = sum(total_claims, na.rm = TRUE),\n  claim_record_rate = mean(claim_flag, na.rm = TRUE),\n  p99_loss_ratio = quantile(loss_ratio, 0.99, na.rm = TRUE)\n)\n\nportfolio_display <- data.frame(\n  Metric = c(\n    \"Valid records\",\n    \"Unique insured customers\",\n    \"Total premium\",\n    \"Total incurred claims\",\n    \"Underwriting result\",\n    \"Portfolio loss ratio\",\n    \"Total claims\",\n    \"Claim record rate\",\n    \"99th percentile loss ratio\"\n  ),\n  Value = c(\n    comma(portfolio_summary$valid_records),\n    comma(portfolio_summary$unique_insured),\n    dollar(portfolio_summary$total_premium, prefix = \"$\"),\n    dollar(portfolio_summary$total_incurred, prefix = \"$\"),\n    dollar(portfolio_summary$underwriting_result, prefix = \"$\"),\n    percent(portfolio_summary$loss_ratio, accuracy = 0.1),\n    comma(portfolio_summary$total_claims),\n    percent(portfolio_summary$claim_record_rate, accuracy = 0.1),\n    percent(portfolio_summary$p99_loss_ratio, accuracy = 0.1)\n  )\n)\n\nknitr::kable(\n  portfolio_display,\n  caption = \"Portfolio-level performance summary\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Portfolio-level performance summary\n\n|Metric                     |Value        |\n|:--------------------------|:------------|\n|Valid records              |354,091      |\n|Unique insured customers   |185,677      |\n|Total premium              |$105,079,669 |\n|Total incurred claims      |$73,864,631  |\n|Underwriting result        |$31,215,039  |\n|Portfolio loss ratio       |70.3%        |\n|Total claims               |77,098       |\n|Claim record rate          |14.3%        |\n|99th percentile loss ratio |70.3%        |\n\n\n:::\n:::\n\n\nThe portfolio contains **354,091** transaction records after filtering for positive premium and exposure. These records belong to **185,677** unique customers, showing that some customers appear more than once for transactions or renewals.\n\nThe portfolio looks **profitable**. It collected about *$105.1 million* in premiums and incurred about *$73.9 million* in claims, giving a positive underwriting result of about *$31.2 million*. The portfolio loss ratio is **70.3%**, which is below 100%, so claims did not exceed premiums. Only **14.3%** of records had claims, which means most records did not make a claim. However, there were still **77,098** claims in total. This suggests that the volatility comes from policies with more expensive claims.\n\nOverall, the portfolio is profitable overall, but further analysis is needed to find which variables are less profitable or more volatile.\n\n## 5. Objective 1: Univariate Visual Analytics\nThis section applies suitable univariate visual analytics techniques to explore the distributions and characteristics of numerical and categorical variables.\n\n### 5.1 Distribution of Key Financial Variables\nHistograms are suitable for identifying skewness, zero inflation and long-tail behaviour in numerical variables.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np1 <- ggplot(motor, aes(x = total_premium)) +\n  geom_histogram(bins = 45, fill = \"#e75480\", colour = \"white\") +\n  scale_x_continuous(labels = label_number()) +\n  labs(\n    title = \"Total premium\",\n    x = \"Total premium\",\n    y = \"Number of records\"\n  )\n\np2 <- ggplot(motor, aes(x = total_incurred)) +\n  geom_histogram(bins = 45, fill = \"#e75480\", colour = \"white\") +\n  scale_x_continuous(labels = label_number()) +\n  labs(\n    title = \"Total incurred claims\",\n    x = \"Total incurred claims\",\n    y = \"Number of records\"\n  )\n\np3 <- ggplot(motor, aes(x = loss_ratio_capped)) +\n  geom_histogram(bins = 45, fill = \"#e75480\", colour = \"white\") +\n  scale_x_continuous(labels = label_number()) +\n  labs(\n    title = \"Loss ratio, capped at 99th percentile\",\n    x = \"Loss ratio\",\n    y = \"Number of records\"\n  )\n\np4 <- ggplot(motor, aes(x = underwriting_result)) +\n  geom_histogram(bins = 45, fill = \"#e75480\", colour = \"white\") +\n  scale_x_continuous(labels = label_number()) +\n  labs(\n    title = \"Underwriting result\",\n    x = \"Underwriting result\",\n    y = \"Number of records\"\n  )\n\np1 + p2 + p3 + p4\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe distributions show that the financial variables are highly skewed. Most records have low premiums and little or no incurred claims, so the bars are heavily concentrated near zero. This means the portfolio is generally stable for most policies. However, the underwriting result shows a few large negative cases, suggesting that profitability can still be affected by a small number of high-claim records.\n\n### 5.2 Distribution of Customer and Vehicle Characteristics\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np5 <- ggplot(motor, aes(x = driver_age)) +\n  geom_histogram(bins = 40, fill = \"#e75480\", colour = \"white\") +\n  labs(\n    title = \"Driver age\",\n    x = \"Driver age\",\n    y = \"Number of records\"\n  )\n\np6 <- ggplot(motor, aes(x = vehicle_value)) +\n  geom_histogram(bins = 40, fill = \"#e75480\", colour = \"white\") +\n  scale_x_continuous(labels = label_number()) +\n  labs(\n    title = \"Vehicle value\",\n    x = \"Vehicle value\",\n    y = \"Number of records\"\n  )\n\np5 + p6 \n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nFrom the plot, we can say that most drivers are *middle-aged*, while vehicle value is highly skewed, meaning most vehicles have *lower values*, with only a small number of very high-value vehicles.\n\n### 5.3 Distribution of Claim Count\nBecause claim count is a discrete numerical variable, a bar chart is more suitable than a histogram.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nclaims_tbl <- mutate(\n  motor,\n  claims_group = if_else(total_claims >= 4, \"4+\", as.character(total_claims))\n)\n\nclaims_tbl <- count(claims_tbl, claims_group)\n\nclaims_tbl <- mutate(\n  claims_tbl,\n  claims_group = factor(claims_group, levels = c(\"0\", \"1\", \"2\", \"3\", \"4+\")),\n  pct = n / sum(n)\n)\n\nggplot(claims_tbl, aes(x = claims_group, y = pct)) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(\n    aes(label = percent(pct, accuracy = 0.1)),\n    vjust = -0.4,\n    size = 3.5\n  ) +\n  scale_y_continuous(\n    labels = percent,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    title = \"Percentage of Claims\",\n    x = \"Total claims per record\",\n    y = \"Share of records\"\n  )\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nMost records did not make any claims, showing that claims are uncommon in the portfolio. This also explains portfolio risk is driven by the smaller number of records with claims.\n\n### 5.4 Categorical portfolio composition\nBar charts are suitable for categorical variables because they show how portfolio volume is distributed across policy, status, business and payment frequency categories.\n\n::: {.panel-tabset}\n## Policy Type\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npolicy_tbl <- count(motor, policy_type)\npolicy_tbl <- mutate(policy_tbl, pct = n / sum(n))\n\np_policy <- ggplot(policy_tbl, aes(x = n, y = fct_reorder(policy_type, n))) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)), hjust = -0.1, size = 3) +\n  scale_x_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Policy type\",\n    x = \"Number of records\",\n    y = NULL\n  )\np_policy\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n**CC (Third-party liability)** is the dominant category, making up **57.8%** of records, followed by **COMP_E (comprehensive with excess)** at **25.8%**. The portfolio is mainly concentrated in these two product types.\n\n## Policy Status\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nstatus_tbl <- count(motor, policy_status)\nstatus_tbl <- mutate(status_tbl, pct = n / sum(n))\n\np_status <- ggplot(status_tbl, aes(x = n, y = fct_reorder(policy_status, n))) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)), hjust = -0.1, size = 3) +\n  scale_x_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Policy status\",\n    x = \"Number of records\",\n    y = NULL\n  )\np_status\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nMost records are active policies, accounting for **89.2%**. Although cancelled policies only accounts for **10.8%**, they should still be checked because it may affect profitability.\n\n## Business Type\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nbusiness_tbl <- count(motor, business_type)\nbusiness_tbl <- mutate(business_tbl, pct = n / sum(n))\n\np_business <- ggplot(business_tbl, aes(x = n, y = fct_reorder(business_type, n))) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)), hjust = -0.1, size = 3) +\n  scale_x_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Business type\",\n    x = \"Number of records\",\n    y = NULL\n  )\np_business\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nNew business records make up **69.3%**. This suggests that the portfolio is more heavily driven by new policy transactions.\n\n## Payment Frequency\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npayment_tbl <- count(motor, payment_frequency)\npayment_tbl <- mutate(payment_tbl, pct = n / sum(n))\n\np_payment <- ggplot(payment_tbl, aes(x = n, y = fct_reorder(payment_frequency, n))) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)), hjust = -0.1, size = 3) +\n  scale_x_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Payment frequency\",\n    x = \"Number of records\",\n    y = NULL\n  )\np_payment\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n**Annual** payment is the most common at **81.3%**. **Semi-annual** and **quarterly** payments are much smaller groups, but they maybe still useful for analysis because payment behaviour can be related to customer profile and profitability.\n:::\n\n## 6. Objective 2: Bivariate Visual Analytics\nThis section applies suitable bivariate visual analytics techniques to investigate factors influencing portfolio profitability and volatility. Statistical validation is included to check whether the visual differences are supported by formal tests.\n\n### 6.1 Profitability and volatility over time\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nyear_perf <- group_by(motor, year)\n\nyear_perf <- summarise(\n  year_perf,\n  total_premium = sum(total_premium, na.rm = TRUE),\n  total_incurred = sum(total_incurred, na.rm = TRUE),\n  loss_ratio = total_incurred / total_premium\n)\n\nggplot(year_perf, aes(x = year, y = loss_ratio)) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    vjust = -0.4,\n    size = 3.5\n  ) +\n  scale_y_continuous(labels = percent, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Portfolio loss ratio by year\",\n    x = \"Year\",\n    y = \"Loss ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nThe portfolio remained profitable across all three years because the loss ratio stayed below 100%. However, the loss ratio increased in 2024, suggesting that profitability weakened compared with 2022 and 2023.\n\n::: {.callout-note}\nA higher loss ratio means weaker profitability.\n:::\n\n### 6.2 Policy type as a profitability driver\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npolicy_perf <- group_by(motor, policy_type)\n\npolicy_perf <- summarise(\n  policy_perf,\n  records = n(),\n  premium = sum(total_premium, na.rm = TRUE),\n  incurred = sum(total_incurred, na.rm = TRUE),\n  loss_ratio = incurred / premium\n)\n\nggplot(policy_perf, aes(x = loss_ratio, y = reorder(policy_type, loss_ratio))) +\n  geom_col(fill = \"#e75480\") +\n  geom_text(\n    aes(label = percent(loss_ratio, accuracy = 0.1)),\n    hjust = -0.1,\n    size = 3\n  ) +\n  scale_x_continuous(\n    labels = percent,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    title = \"Loss ratio by policy type\",\n    x = \"Loss ratio\",\n    y = \"Policy type\"\n  )\n```\n\n::: {.cell-output-display}\n![](TakeHome1_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "TakeHome1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}